services:
  db:
    image: mysql:8.0
    container_name: portfolio_db
    environment:
      MYSQL_DATABASE: ${DB_NAME:-portfolio}
      MYSQL_USER: ${DB_USER:-portfolio}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: portfolio_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-portfolio}
      DB_USER: ${DB_USER:-portfolio}
      DB_PASSWORD: ${DB_PASSWORD:-secret}

  frontend:
    build: ./frontend
    container_name: portfolio_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db_data:

