services:
  db:
    image: postgres:16
    container_name: portfolio_db
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-Sunnysandy@1}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: portfolio_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-postgres}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-Sunnysandy@1}
      JWT_SECRET: ${JWT_SECRET:-dev-secret-change-me-1234567890123456}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-3600000}

  frontend:
    build: ./frontend
    container_name: portfolio_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db_data: