services:
  db:
    restart: unless-stopped

  backend:
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
    ports:
      - "${BACKEND_PORT:-8080}:8080"

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-/api}
    ports:
      - "${FRONTEND_PORT:-80}:80"
